# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/top_bd_swerv_eh1_reference_0_6.xci
# IP: The module: 'top_bd_swerv_eh1_reference_0_6' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/axi_intc/ip/axi_intc_auto_cc_1/axi_intc_auto_cc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_intc_auto_cc_1 || ORIG_REF_NAME==axi_intc_auto_cc_1} -quiet] -quiet

# IP: /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/axi_intc/ip/axi_intc_auto_cc_4/axi_intc_auto_cc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_intc_auto_cc_4 || ORIG_REF_NAME==axi_intc_auto_cc_4} -quiet] -quiet

# IP: /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/axi_intc/ip/axi_intc_auto_cc_0/axi_intc_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_intc_auto_cc_0 || ORIG_REF_NAME==axi_intc_auto_cc_0} -quiet] -quiet

# IP: /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/axi_intc/ip/axi_intc_auto_cc_2/axi_intc_auto_cc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_intc_auto_cc_2 || ORIG_REF_NAME==axi_intc_auto_cc_2} -quiet] -quiet

# IP: /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/axi_intc/ip/axi_intc_auto_cc_3/axi_intc_auto_cc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_intc_auto_cc_3 || ORIG_REF_NAME==axi_intc_auto_cc_3} -quiet] -quiet

# IP: /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/axi_intc/ip/axi_intc_auto_pc_0/axi_intc_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_intc_auto_pc_0 || ORIG_REF_NAME==axi_intc_auto_pc_0} -quiet] -quiet

# IP: /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/clk_and_rst/ip/clk_and_rst_proc_sys_reset_0_0/clk_and_rst_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_and_rst_proc_sys_reset_0_0 || ORIG_REF_NAME==clk_and_rst_proc_sys_reset_0_0} -quiet] -quiet

# IP: /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/clk_and_rst/ip/clk_and_rst_clk_wiz_0/clk_and_rst_clk_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_and_rst_clk_wiz_0 || ORIG_REF_NAME==clk_and_rst_clk_wiz_0} -quiet] -quiet

# IP: /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/axi_intc/ip/axi_intc_xbar_0/axi_intc_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_intc_xbar_0 || ORIG_REF_NAME==axi_intc_xbar_0} -quiet] -quiet

# IP: /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/axi_intc/ip/axi_intc_axi_bram_ctrl_0_0/axi_intc_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_intc_axi_bram_ctrl_0_0 || ORIG_REF_NAME==axi_intc_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/axi_intc/ip/axi_intc_blk_mem_gen_0_0/axi_intc_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_intc_blk_mem_gen_0_0 || ORIG_REF_NAME==axi_intc_blk_mem_gen_0_0} -quiet] -quiet

# IP: /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/axi_intc/ip/axi_intc_axi_uartlite_0_0/axi_intc_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_intc_axi_uartlite_0_0 || ORIG_REF_NAME==axi_intc_axi_uartlite_0_0} -quiet] -quiet

# XDC: /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/axi_intc/ip/axi_intc_auto_cc_1/axi_intc_auto_cc_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_intc_auto_cc_1 || ORIG_REF_NAME==axi_intc_auto_cc_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/axi_intc/ip/axi_intc_auto_cc_1/axi_intc_auto_cc_1_ooc.xdc

# XDC: /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/axi_intc/ip/axi_intc_auto_cc_4/axi_intc_auto_cc_4_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_intc_auto_cc_4 || ORIG_REF_NAME==axi_intc_auto_cc_4} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/axi_intc/ip/axi_intc_auto_cc_4/axi_intc_auto_cc_4_ooc.xdc

# XDC: /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/axi_intc/ip/axi_intc_auto_cc_0/axi_intc_auto_cc_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_intc_auto_cc_0 || ORIG_REF_NAME==axi_intc_auto_cc_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/axi_intc/ip/axi_intc_auto_cc_0/axi_intc_auto_cc_0_ooc.xdc

# XDC: /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/axi_intc/ip/axi_intc_auto_cc_2/axi_intc_auto_cc_2_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_intc_auto_cc_2 || ORIG_REF_NAME==axi_intc_auto_cc_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/axi_intc/ip/axi_intc_auto_cc_2/axi_intc_auto_cc_2_ooc.xdc

# XDC: /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/axi_intc/ip/axi_intc_auto_cc_3/axi_intc_auto_cc_3_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_intc_auto_cc_3 || ORIG_REF_NAME==axi_intc_auto_cc_3} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/axi_intc/ip/axi_intc_auto_cc_3/axi_intc_auto_cc_3_ooc.xdc

# XDC: /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/axi_intc/ip/axi_intc_auto_pc_0/axi_intc_auto_pc_0_ooc.xdc

# XDC: /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/clk_and_rst/ip/clk_and_rst_proc_sys_reset_0_0/clk_and_rst_proc_sys_reset_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_and_rst_proc_sys_reset_0_0 || ORIG_REF_NAME==clk_and_rst_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/clk_and_rst/ip/clk_and_rst_clk_wiz_0/clk_and_rst_clk_wiz_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_and_rst_clk_wiz_0 || ORIG_REF_NAME==clk_and_rst_clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/clk_and_rst/ip/clk_and_rst_clk_wiz_0/clk_and_rst_clk_wiz_0_ooc.xdc

# XDC: /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/axi_intc/ip/axi_intc_blk_mem_gen_0_0/axi_intc_blk_mem_gen_0_0_ooc.xdc

# XDC: /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/axi_intc/ip/axi_intc_axi_uartlite_0_0/axi_intc_axi_uartlite_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_intc_axi_uartlite_0_0 || ORIG_REF_NAME==axi_intc_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/axi_intc/ip/axi_intc_axi_uartlite_0_0/axi_intc_axi_uartlite_0_0_ooc.xdc

# XDC: /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/axi_intc/ip/axi_intc_axi_uartlite_0_0/axi_intc_axi_uartlite_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_intc_axi_uartlite_0_0 || ORIG_REF_NAME==axi_intc_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/clk_and_rst/clk_and_rst_ooc.xdc

# IP: /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/top_bd_swerv_eh1_reference_0_6.xci
# IP: The module: 'top_bd_swerv_eh1_reference_0_6' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/axi_intc/ip/axi_intc_auto_cc_1/axi_intc_auto_cc_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_intc_auto_cc_1 || ORIG_REF_NAME==axi_intc_auto_cc_1} -quiet] -quiet

# IP: /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/axi_intc/ip/axi_intc_auto_cc_4/axi_intc_auto_cc_4.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_intc_auto_cc_4 || ORIG_REF_NAME==axi_intc_auto_cc_4} -quiet] -quiet

# IP: /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/axi_intc/ip/axi_intc_auto_cc_0/axi_intc_auto_cc_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_intc_auto_cc_0 || ORIG_REF_NAME==axi_intc_auto_cc_0} -quiet] -quiet

# IP: /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/axi_intc/ip/axi_intc_auto_cc_2/axi_intc_auto_cc_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_intc_auto_cc_2 || ORIG_REF_NAME==axi_intc_auto_cc_2} -quiet] -quiet

# IP: /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/axi_intc/ip/axi_intc_auto_cc_3/axi_intc_auto_cc_3.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_intc_auto_cc_3 || ORIG_REF_NAME==axi_intc_auto_cc_3} -quiet] -quiet

# IP: /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/axi_intc/ip/axi_intc_auto_pc_0/axi_intc_auto_pc_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_intc_auto_pc_0 || ORIG_REF_NAME==axi_intc_auto_pc_0} -quiet] -quiet

# IP: /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/clk_and_rst/ip/clk_and_rst_proc_sys_reset_0_0/clk_and_rst_proc_sys_reset_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_and_rst_proc_sys_reset_0_0 || ORIG_REF_NAME==clk_and_rst_proc_sys_reset_0_0} -quiet] -quiet

# IP: /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/clk_and_rst/ip/clk_and_rst_clk_wiz_0/clk_and_rst_clk_wiz_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_and_rst_clk_wiz_0 || ORIG_REF_NAME==clk_and_rst_clk_wiz_0} -quiet] -quiet

# IP: /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/axi_intc/ip/axi_intc_xbar_0/axi_intc_xbar_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_intc_xbar_0 || ORIG_REF_NAME==axi_intc_xbar_0} -quiet] -quiet

# IP: /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/axi_intc/ip/axi_intc_axi_bram_ctrl_0_0/axi_intc_axi_bram_ctrl_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_intc_axi_bram_ctrl_0_0 || ORIG_REF_NAME==axi_intc_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/axi_intc/ip/axi_intc_blk_mem_gen_0_0/axi_intc_blk_mem_gen_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_intc_blk_mem_gen_0_0 || ORIG_REF_NAME==axi_intc_blk_mem_gen_0_0} -quiet] -quiet

# IP: /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/axi_intc/ip/axi_intc_axi_uartlite_0_0/axi_intc_axi_uartlite_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_intc_axi_uartlite_0_0 || ORIG_REF_NAME==axi_intc_axi_uartlite_0_0} -quiet] -quiet

# XDC: /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/axi_intc/ip/axi_intc_auto_cc_1/axi_intc_auto_cc_1_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_intc_auto_cc_1 || ORIG_REF_NAME==axi_intc_auto_cc_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/axi_intc/ip/axi_intc_auto_cc_1/axi_intc_auto_cc_1_ooc.xdc

# XDC: /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/axi_intc/ip/axi_intc_auto_cc_4/axi_intc_auto_cc_4_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_intc_auto_cc_4 || ORIG_REF_NAME==axi_intc_auto_cc_4} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/axi_intc/ip/axi_intc_auto_cc_4/axi_intc_auto_cc_4_ooc.xdc

# XDC: /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/axi_intc/ip/axi_intc_auto_cc_0/axi_intc_auto_cc_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_intc_auto_cc_0 || ORIG_REF_NAME==axi_intc_auto_cc_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/axi_intc/ip/axi_intc_auto_cc_0/axi_intc_auto_cc_0_ooc.xdc

# XDC: /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/axi_intc/ip/axi_intc_auto_cc_2/axi_intc_auto_cc_2_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_intc_auto_cc_2 || ORIG_REF_NAME==axi_intc_auto_cc_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/axi_intc/ip/axi_intc_auto_cc_2/axi_intc_auto_cc_2_ooc.xdc

# XDC: /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/axi_intc/ip/axi_intc_auto_cc_3/axi_intc_auto_cc_3_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_intc_auto_cc_3 || ORIG_REF_NAME==axi_intc_auto_cc_3} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/axi_intc/ip/axi_intc_auto_cc_3/axi_intc_auto_cc_3_ooc.xdc

# XDC: /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/axi_intc/ip/axi_intc_auto_pc_0/axi_intc_auto_pc_0_ooc.xdc

# XDC: /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/clk_and_rst/ip/clk_and_rst_proc_sys_reset_0_0/clk_and_rst_proc_sys_reset_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_and_rst_proc_sys_reset_0_0 || ORIG_REF_NAME==clk_and_rst_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/clk_and_rst/ip/clk_and_rst_clk_wiz_0/clk_and_rst_clk_wiz_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_and_rst_clk_wiz_0 || ORIG_REF_NAME==clk_and_rst_clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/clk_and_rst/ip/clk_and_rst_clk_wiz_0/clk_and_rst_clk_wiz_0_ooc.xdc

# XDC: /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/axi_intc/ip/axi_intc_blk_mem_gen_0_0/axi_intc_blk_mem_gen_0_0_ooc.xdc

# XDC: /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/axi_intc/ip/axi_intc_axi_uartlite_0_0/axi_intc_axi_uartlite_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_intc_axi_uartlite_0_0 || ORIG_REF_NAME==axi_intc_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/axi_intc/ip/axi_intc_axi_uartlite_0_0/axi_intc_axi_uartlite_0_0_ooc.xdc

# XDC: /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/axi_intc/ip/axi_intc_axi_uartlite_0_0/axi_intc_axi_uartlite_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_intc_axi_uartlite_0_0 || ORIG_REF_NAME==axi_intc_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/clk_and_rst/clk_and_rst_ooc.xdc
