# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/swerv.xdc

# Block Designs: bd/top_bd/top_bd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_bd || ORIG_REF_NAME==top_bd} -quiet] -quiet

# IP: bd/top_bd/ip/top_bd_processing_system7_0_0/top_bd_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_bd_processing_system7_0_0 || ORIG_REF_NAME==top_bd_processing_system7_0_0} -quiet] -quiet

# IP: bd/top_bd/ip/top_bd_axi_emc_0_0/top_bd_axi_emc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_bd_axi_emc_0_0 || ORIG_REF_NAME==top_bd_axi_emc_0_0} -quiet] -quiet

# IP: bd/top_bd/ip/top_bd_axi_smc_0/top_bd_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_bd_axi_smc_0 || ORIG_REF_NAME==top_bd_axi_smc_0} -quiet] -quiet

# IP: bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/top_bd_swerv_eh1_reference_0_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_bd_swerv_eh1_reference_0_6 || ORIG_REF_NAME==top_bd_swerv_eh1_reference_0_6} -quiet] -quiet

# IP: bd/top_bd/ip/top_bd_proc_sys_reset_0_0/top_bd_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_bd_proc_sys_reset_0_0 || ORIG_REF_NAME==top_bd_proc_sys_reset_0_0} -quiet] -quiet

# XDC: bd/top_bd/top_bd_ooc.xdc
