# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z100ffg900-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.cache/wt [current_project]
set_property parent.project_path /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:mini_module_plus_7z100_rev_c:part0:1.0 [current_project]
set_property ip_repo_paths /home/lqa/Documents/swerv/swerv_eh1_core [current_project]
update_ip_catalog
set_property ip_output_repo /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/hdl/top_bd_wrapper.v
add_files /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/top_bd.bd
set_property is_enabled false [get_files -all /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/clk_and_rst/ip/clk_and_rst_proc_sys_reset_0_0/clk_and_rst_proc_sys_reset_0_0_board.xdc]
set_property is_enabled false [get_files -all /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/clk_and_rst/ip/clk_and_rst_clk_wiz_0/clk_and_rst_clk_wiz_0_board.xdc]
set_property is_enabled false [get_files -all /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/axi_intc/axi_intc_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_processing_system7_0_0/top_bd_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_axi_emc_0_0/top_bd_axi_emc_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_axi_emc_0_0/top_bd_axi_emc_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_axi_emc_0_0/top_bd_axi_emc_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_axi_smc_0/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_axi_smc_0/bd_0/ip/ip_1/bd_c78a_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_axi_smc_0/bd_0/ip/ip_1/bd_c78a_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_axi_smc_0/bd_0/ip/ip_5/bd_c78a_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_axi_smc_0/bd_0/ip/ip_6/bd_c78a_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_axi_smc_0/bd_0/ip/ip_7/bd_c78a_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_axi_smc_0/bd_0/ip/ip_8/bd_c78a_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_axi_smc_0/bd_0/ip/ip_9/bd_c78a_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_axi_smc_0/bd_0/ip/ip_10/bd_c78a_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_axi_smc_0/bd_0/ip/ip_11/bd_c78a_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/clk_and_rst/clk_and_rst_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/axi_intc/ip/axi_intc_auto_cc_1/axi_intc_auto_cc_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/axi_intc/ip/axi_intc_auto_cc_1/axi_intc_auto_cc_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/axi_intc/ip/axi_intc_auto_cc_1/axi_intc_auto_cc_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/axi_intc/ip/axi_intc_auto_cc_4/axi_intc_auto_cc_4_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/axi_intc/ip/axi_intc_auto_cc_4/axi_intc_auto_cc_4_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/axi_intc/ip/axi_intc_auto_cc_4/axi_intc_auto_cc_4_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/axi_intc/ip/axi_intc_auto_cc_0/axi_intc_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/axi_intc/ip/axi_intc_auto_cc_0/axi_intc_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/axi_intc/ip/axi_intc_auto_cc_0/axi_intc_auto_cc_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/axi_intc/ip/axi_intc_auto_cc_2/axi_intc_auto_cc_2_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/axi_intc/ip/axi_intc_auto_cc_2/axi_intc_auto_cc_2_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/axi_intc/ip/axi_intc_auto_cc_2/axi_intc_auto_cc_2_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/axi_intc/ip/axi_intc_auto_cc_3/axi_intc_auto_cc_3_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/axi_intc/ip/axi_intc_auto_cc_3/axi_intc_auto_cc_3_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/axi_intc/ip/axi_intc_auto_cc_3/axi_intc_auto_cc_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/axi_intc/ip/axi_intc_auto_pc_0/axi_intc_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/clk_and_rst/ip/clk_and_rst_proc_sys_reset_0_0/clk_and_rst_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/clk_and_rst/ip/clk_and_rst_clk_wiz_0/clk_and_rst_clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/clk_and_rst/ip/clk_and_rst_clk_wiz_0/clk_and_rst_clk_wiz_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/axi_intc/ip/axi_intc_blk_mem_gen_0_0/axi_intc_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/axi_intc/ip/axi_intc_axi_uartlite_0_0/axi_intc_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/axi_intc/ip/axi_intc_axi_uartlite_0_0/axi_intc_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_swerv_eh1_reference_0_6/swerv_eh1_core.srcs/sources_1/bd/axi_intc/ip/axi_intc_axi_uartlite_0_0/axi_intc_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_proc_sys_reset_0_0/top_bd_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_proc_sys_reset_0_0/top_bd_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_proc_sys_reset_0_0/top_bd_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/top_bd_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/constrs_1/new/swerv.xdc
set_property used_in_implementation false [get_files /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/constrs_1/new/swerv.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top_bd_wrapper -part xc7z100ffg900-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_bd_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_bd_wrapper_utilization_synth.rpt -pb top_bd_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
