# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_proc_sys_reset_0_0/top_bd_proc_sys_reset_0_0.xci
# IP: The module: 'top_bd_proc_sys_reset_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_proc_sys_reset_0_0/top_bd_proc_sys_reset_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_bd_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_proc_sys_reset_0_0/top_bd_proc_sys_reset_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_bd_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_proc_sys_reset_0_0/top_bd_proc_sys_reset_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_bd_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_proc_sys_reset_0_0/top_bd_proc_sys_reset_0_0.xci
# IP: The module: 'top_bd_proc_sys_reset_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_proc_sys_reset_0_0/top_bd_proc_sys_reset_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_bd_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_proc_sys_reset_0_0/top_bd_proc_sys_reset_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_bd_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/lqa/Documents/swerv/swerv_core_fpga/swerv_core_fpga.srcs/sources_1/bd/top_bd/ip/top_bd_proc_sys_reset_0_0/top_bd_proc_sys_reset_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_bd_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
